version: "3"
services: 
  # Cousul is just for local debugging and will be replaced by k8s in prod
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    restart: always    
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"  
  nats:
    image: nats:1.1.0-linux
    ports:
    - "4222:4222"
    - "8222:8222"